---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8app 
spec:
  replicas: 2
  selector:
   matchLabels:
    app: k8app
  template:
    metadata:
      labels:
        app: k8app
    spec:
      containers:
      - name: k8app
        image: rahulk2020/k8image:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8app-svc
  labels:
    app: k8app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: k8app
